/*
  optimize-images.mjs — responsive-image pipeline for the artwork gallery.

  On a fine-art site the paintings ARE the product, so their weight directly
  cheapens the experience. The grid used to ship ~735×1100 JPEGs (~200–360 KB
  each × 66 works ≈ 15–24 MB per gallery page). This generates properly
  compressed, RESPONSIVE WebP sizes so the browser only ever downloads what a
  given slot needs, and a tiny inlined blur placeholder so paintings develop in
  like film instead of popping.

  - Source of truth: public/images/artwork/** (originals are left untouched).
  - Derived output:  public/images/derived/<relpath>/<name>-<w>.webp
  - Manifest:        src/lib/imgManifest.js  (which widths exist + LQIP blur)

  Uses `sharp` (already a devDependency — much better compression + WebP than
  the macOS `sips` the old thumbnail script leaned on). Idempotent: re-run any
  time art is added; existing derivatives are skipped unless --force.

  Run:  node scripts/optimize-images.mjs [--force]
*/
import sharp from "sharp";
import { readdir, mkdir, stat, writeFile } from "fs/promises";
import { existsSync } from "fs";
import { join, dirname, extname, basename, relative, sep } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const publicDir = join(root, "public");
const artworkDir = join(publicDir, "images", "artwork");
const derivedRoot = join(publicDir, "images", "derived");
const manifestPath = join(root, "src", "lib", "imgManifest.js");

const WIDTHS = [400, 640, 900, 1400, 2000];
const WEBP = { quality: 80, effort: 5 };
const IMG_RE = /\.(jpe?g|png|jfif|webp)$/i;
const FORCE = process.argv.includes("--force");

// Directories we never descend into (legacy near-full "thumbnails" + scratch).
const SKIP_DIRS = new Set(["thumbnails"]);

async function walk(dir) {
  const out = [];
  for (const name of await readdir(dir)) {
    if (name.startsWith(".") || name.startsWith("_")) continue;
    const p = join(dir, name);
    const s = await stat(p);
    if (s.isDirectory()) {
      if (SKIP_DIRS.has(name)) continue;
      out.push(...(await walk(p)));
    } else if (IMG_RE.test(name)) {
      out.push(p);
    }
  }
  return out;
}

function toWebPath(absPath) {
  // absolute fs path under /public → web path ("/images/…")
  return "/" + relative(publicDir, absPath).split(sep).join("/");
}

async function run() {
  const files = await walk(artworkDir);
  files.sort();
  const manifest = {};
  let generated = 0;
  let bytesOut = 0;

  for (const src of files) {
    const meta = await sharp(src).metadata();
    const srcWidth = meta.width || 0;
    const rel = relative(publicDir, src); // images/artwork/awakening/05-Red-Coral-I.jpg
    const relDir = dirname(rel);
    const name = basename(src, extname(src));
    const outDir = join(derivedRoot, relative(join(publicDir, "images"), join(publicDir, relDir)));
    await mkdir(outDir, { recursive: true });

    // Only emit widths we actually have pixels for (never upscale a painting).
    const targets = WIDTHS.filter((w) => w <= srcWidth);
    if (targets.length === 0) targets.push(srcWidth); // tiny source: one native-size webp
    const widthsMade = [];

    for (const w of targets) {
      const outPath = join(outDir, `${name}-${w}.webp`);
      if (!FORCE && existsSync(outPath)) {
        widthsMade.push(w);
        bytesOut += (await stat(outPath)).size;
        continue;
      }
      const info = await sharp(src)
        .resize(w, null, { withoutEnlargement: true })
        .webp(WEBP)
        .toFile(outPath);
      widthsMade.push(w);
      bytesOut += info.size;
      generated++;
    }

    // LQIP — a ~24px blurred WebP inlined as a data URI (film-develop blur-up).
    const blurBuf = await sharp(src)
      .resize(24, null, { withoutEnlargement: true })
      .blur(1.2)
      .webp({ quality: 40 })
      .toBuffer();
    const blur = `data:image/webp;base64,${blurBuf.toString("base64")}`;

    const webPath = toWebPath(src); // /images/artwork/…
    const base = "/images/derived/" + relative(join(publicDir, "images"), join(publicDir, relDir)).split(sep).join("/") + "/" + name;
    manifest[webPath] = {
      base,                       // derived basename; append `-<w>.webp`
      widths: widthsMade.sort((a, b) => a - b),
      w: srcWidth,
      h: meta.height || 0,
      blur,
    };
  }

  const header =
    "// AUTO-GENERATED by scripts/optimize-images.mjs — do not edit by hand.\n" +
    "// Maps each original artwork path to its responsive WebP derivatives +\n" +
    "// an inlined LQIP blur. Consumed by src/lib/img.js.\n";
  await writeFile(
    manifestPath,
    header + "export const IMG_MANIFEST = " + JSON.stringify(manifest, null, 0) + ";\n"
  );

  console.log(`\n✓ ${files.length} source paintings → ${generated} new WebP derivatives`);
  console.log(`  derived payload on disk: ${(bytesOut / 1e6).toFixed(1)} MB across all sizes`);
  console.log(`  manifest: ${relative(root, manifestPath)} (${files.length} entries)`);
}

run().catch((e) => {
  console.error(e);
  process.exit(1);
});
